### ISSUE TITLE
After click on "Connect" nothing happen

### ISSUE THREAD

**Issue by holdav** [Azakur4/brackets-database#1]
Hello,

I want to connect to my DB via your plugin in Brackets. I fill all of fileds, but after click on "Connect" button nothing happen. Even no error messages such as "Bad password" or something like this. Can you give me some solution?

Thanks.

**Comment by Azakur4** [comment]
Hi man sorry for my late response i will try to review the code to add more error or info message in the console to see what is happen but i can only see that to end of the week maybe.

If u don't want wait feel free to fork this and make a pull request :) all help is welcome.

**Comment by holdav** [comment]
So, you claim, that the plugin is not broken and connection to DB works well, only I put incorrect values into the login fields? If it is true, please can you give me some testing DB connection values which works or simpy record some video, where is connection to DB succesfful? I have tried many connections, with the same bad result. But in phpMyAdmin or in my PHP scripts the same mySQL connection works well. Thank you for every advice.

**Comment by Azakur4** [comment]
can u see if ur database accept remote connections or u are trying to connect a localhost database?

**Comment by holdav** [comment]
Sorry for my late response. I am trying to connect to remote DB.

**Comment by Azakur4** [comment]
i understand, can u try connect to the database that give u problems with a mysql client like mysql workbench to see what happens?

**Comment by holdav** [comment]
I have tried to connect to remote DB in Navicat and it shows me error number 10038 and I can't solve it yet. But localhost DB works well in Navicat, I can connect to localhost, so I tried to connect to localhost via your plugin in Brackets too and it was connected successfull, but there was no reaction on "Run" and "List tables" buttons. I found out, that if I leave all inputs blank it connect me as well, so all about this thing is very strange.

**Comment by Azakur4** [comment]
umm probably the remote DB not accept remote connections with the account that u are using.

well now for localhost doesn't have ideia why not work, actually im not working in this plugin cuz i leave brackets. i think i will come back in the future im waiting for new releases.
